import autoprefixer from 'autoprefixer';

// This PostCSS config runs autoprefixer on the CSS output generated by Tailwind via the
// @tailwindcss/vite plugin. Vite will automatically pick up this config.
export default {
  plugins: [
    // Tailwind is handled by the Vite plugin; we just add autoprefixer here.
    autoprefixer()
  ]
};
